#!/bin/sh

# Open files by content.
#
# Usage:
#
# kamp-grep [paths]

# – fzf (https://github.com/junegunn/fzf)
# – ripgrep (https://github.com/BurntSushi/ripgrep)

# Not pretty but robust.
# https://github.com/junegunn/fzf/issues/2581
export PATHS_PATH=$(mktemp)
trap 'rm "$PATHS_PATH"' EXIT
for path do
  echo "$path" >> "$PATHS_PATH"
done

SHELL=sh \
fzf \
  --phony \
  --delimiter ':' \
  --ansi \
  --bind 'change:reload(
            while read path; do
              set -- "$@" "$path"
            done < "$PATHS_PATH"
            rg \
              --color=always \
              --column \
              --with-filename \
              --fixed-strings "$@" -- {q} || true
          ),enter:execute(
            kamp edit {1} +{2}:{3}
          )+abort' \
  --preview '
      highlight_line={2}
      line_range_begin=$((highlight_line - (FZF_PREVIEW_LINES / 2)))
      bat \
        --style=numbers \
        --color=always \
        --line-range "$((line_range_begin < 0 ? 1 : line_range_begin)):+$FZF_PREVIEW_LINES" \
        --highlight-line {2} {1} 2> /dev/null' \
  --header='Select a file to open' \
  --prompt='grep>'
