#!/bin/sh
#
# pick files
#
# requires:
# - fd (https://github.com/sharkdp/fd)
# - fzf (https://github.com/junegunn/fzf)
# - bat (change to your liking) (https://github.com/sharkdp/bat)

preview_cmd="bat --color=always --line-range=:500 {}"

fd --type file . "$@" |
    fzf --multi --height 100% --prompt 'files> ' --preview "$preview_cmd" |
    while read -r file; do
        kamp edit "$file"
    done
