#!/bin/sh
#
# Open files by content.
#
# Usage:
#
# kamp-grep [<query=...>] [rg_options]

# requires:
# – fzf (https://github.com/junegunn/fzf)
  # https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0190
# – ripgrep (https://github.com/BurntSushi/ripgrep)
  # 'rg --no-heading --with-filename' are defaults when not printing to a terminal
  # 'rg --column' implies --line-number
# - bat (https://github.com/sharkdp/bat)

set -euf

# define SHELL so --preview arguments do not error if current SHELL is not POSIX
SHELL=/bin/sh

query=""

if [ $# -ne 0 ]; then
  case "$1" in
    query=*)
      query="${1#*=}"
      shift
    ;;
  esac
fi

rg_cmd="rg $*"

if [ -z "$query" ]; then
  export FZF_DEFAULT_COMMAND="$rg_cmd --files"
else
  export FZF_DEFAULT_COMMAND="$rg_cmd --color always --column -- '$query'"
fi

fzf \
  --phony \
  --query "${query:-}" \
  --delimiter ':' \
  --ansi \
  --bind "change:reload($rg_cmd --color always --column -- {q} || true)" \
  --bind 'enter:become(kamp edit {1} +{2}:{3})' \
  --preview '
      highlight_line={2}
      line_range_begin=$((highlight_line - FZF_PREVIEW_LINES / 2))
      bat \
        --terminal-width $FZF_PREVIEW_COLUMNS \
        --style=numbers \
        --color=always \
        --line-range "$((line_range_begin < 0 ? 1 : line_range_begin)):+$FZF_PREVIEW_LINES" \
        --highlight-line {2} {1} 2> /dev/null' \
  --header 'type to grep' \
  --prompt 'grep> '
