#!/bin/sh
#
# pick filetype from Kakoune's runtime dir and set in current buffer
#
# requires:
# - fzf (https://github.com/junegunn/fzf)

runtime="$(kamp get val runtime)"

find "$runtime"/rc/filetype/*.kak -type f -exec basename -s .kak {} \; |
    fzf --no-preview \
        --prompt 'filetypes> ' \
        --bind 'enter:become:kamp send set buffer filetype {}'
