#!/bin/sh
#
# attach session and pick a buffer
#
# requires:
# - fzf (https://github.com/junegunn/fzf)
# - kamp-buffers

set -euf

sessions_cmd='kak -l'
preview_cmd='kamp -s {} list'
kill_cmd='kamp -s {} kill'

eval "$sessions_cmd" |
    fzf --prompt 'session> ' --preview "$preview_cmd" \
        --header '[c-x] kill' \
        --bind "ctrl-x:execute-silent($kill_cmd)+reload($sessions_cmd)" |
    xargs -r -n1 kamp-buffers attach
