#!/bin/sh
#
# pick files
#
# requires:
# - fd (https://github.com/sharkdp/fd)
# - fzf (https://github.com/junegunn/fzf)
# - bat (https://github.com/sharkdp/bat)

set -euf

usage() {
    printf "Usage: %s: [-b <fd|rg|find|git>] [backend_options]\n" "$(basename "$0")" >&2
    exit 2
}

backend="fd"
while getopts 'b:h' OPTION; do
    case $OPTION in
    b)
        backend="$OPTARG"
        ;;
    h|?)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

case "$backend" in
    fd)
        backend_cmd="fd --strip-cwd-prefix --type file"
        ;;
    rg)
        backend_cmd="rg --color never --files"
        ;;
    find)
        backend_cmd="find . -type f"
        ;;
    git)
        backend_cmd="git ls-files"
        ;;
    *)
        usage
        ;;
esac

backend_cmd="$backend_cmd $*"
preview_cmd='bat --color=always --line-range=:500 {}'

eval "$backend_cmd" |
  fzf --multi --prompt "${backend}> " --preview "$preview_cmd" --bind 'enter:become(kamp edit {+})'
