#!/bin/sh
#
# pick filetype from Kakoune's runtime dir and set in current buffer
#
# requires:
# - fzf (https://github.com/junegunn/fzf)

ft_dir="$(kamp get val runtime)/rc/filetype"

find "$ft_dir"/*.kak -type f -exec basename -s .kak {} \; |
	fzf --no-preview --prompt 'filetypes> ' |
	xargs -I {} kamp send 'set buffer filetype {}'
