#!/bin/sh
#
# pick from git ls-files
#
# requires:
# - fzf (https://github.com/junegunn/fzf)
# - bat (change to your liking) (https://github.com/sharkdp/bat)

preview_cmd='bat --color=always --line-range=:500 {}'

git ls-files . "$@" |
    fzf --multi --prompt 'gitls> ' --preview "$preview_cmd" |
    while read -r file; do
        kamp edit "$file"
    done
