#!/bin/sh

# Open files by content.
#
# Usage:
#
# kamp-grep [options]

# – fzf (https://github.com/junegunn/fzf)
# https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0190

# – ripgrep (https://github.com/BurntSushi/ripgrep)
# 'rg --no-heading --with-filename' are default when not printing to a terminal
# 'rg --column' implies --line-number

# - bat (https://github.com/sharkdp/bat)

# $@ is meant to pass extra options to rg, not a query and not a path
rg_cmd="rg --color=always --column --fixed-strings $@"

FZF_DEFAULT_COMMAND="$rg_cmd --files" \
fzf \
  --phony \
  --delimiter ':' \
  --ansi \
  --bind "change:reload($rg_cmd -- {q} || true)" \
  --bind 'enter:execute(kamp edit {1} +{2}:{3})+abort' \
  --preview '
      highlight_line={2}
      line_range_begin=$((highlight_line - (FZF_PREVIEW_LINES / 2)))
      bat \
        --terminal-width $FZF_PREVIEW_COLUMNS \
        --style=numbers \
        --color=always \
        --line-range "$((line_range_begin < 0 ? 1 : line_range_begin)):+$FZF_PREVIEW_LINES" \
        --highlight-line {2} {1} 2> /dev/null' \
  --header='type to grep' \
  --prompt='grep> '
