#!/bin/sh
#
# pick buffers
#
# requires:
# - fzf (https://github.com/junegunn/fzf)
# - bat (https://github.com/sharkdp/bat)
#
# optional param: $1 = attach
# optional param: $2 = session

set -euf

session=""
exec_cmd=""

if [ $# -eq 0 ]; then
    session="$KAKOUNE_SESSION"
    exec_cmd="kamp -s $session -c ${KAKOUNE_CLIENT:-client0} send buffer {}"
elif [ "$1" = "attach" ]; then
    session="${2:-$KAKOUNE_SESSION}"
    exec_cmd="kamp -s $session attach -b {}"
else
    exit 1
fi

buffers_cmd="kamp -s $session get val -b \* -s bufname"
preview_cmd="kamp -s $session cat -b {} | bat --color=always --line-range=:500 --file-name {}"
delete_cmd="kamp -s $session send -b {} delete-buffer"

eval "$buffers_cmd" |
    fzf --prompt 'buf> ' --preview "$preview_cmd" \
        --header '[c-x] delete' \
        --bind "ctrl-x:execute-silent($delete_cmd)+reload($buffers_cmd)" \
        --bind "enter:become($exec_cmd)"
