#!/bin/sh
#
# pick files
#
# Usage:
#
# kamp-files [<backend=fd|rg|find|git>] [backend_options]

# requires:
# - fd (https://github.com/sharkdp/fd)
# - fzf (https://github.com/junegunn/fzf)
# - bat (https://github.com/sharkdp/bat)

set -euf

preview_cmd='bat --color=always --line-range=:500 {}'

backend="fd"
if [ $# -ne 0 ]; then
  case "$1" in
    backend=*)
      backend="${1#*=}"
      shift
    ;;
  esac
fi

backend_cmd=""
case "$backend" in
  fd) backend_cmd="fd --strip-cwd-prefix --color never --type file" ;;
  rg) backend_cmd="rg --color never --files" ;;
  find) backend_cmd="find . -type f" ;;
  git) backend_cmd="git ls-files" ;;
  *) backend_cmd="$backend" ;;
esac

backend_cmd="$backend_cmd $*"

eval "$backend_cmd" |
  fzf --multi --prompt "${backend}> " --preview "$preview_cmd" --bind 'enter:become(kamp edit {+})'
